source 'https://rubygems.org'
ruby "2.5.0"

gem 'sinatra'
gem 'sinatra-cross_origin'
gem 'pry-byebug'
gem 'rack'
gem 'rake'
gem 'byebug'
gem 'rack-test'
gem 'time_difference'
gem 'faker'
gem 'bcrypt'
gem 'redis'
gem 'redis-sinatra'
gem 'sinatra-cors'
gem 'bunny'
gem 'rest-client'
